package info.raa0121.duelsimulation.client

import com.badlogic.gdx.ApplicationListener
import com.badlogic.gdx.backends.gwt.GwtApplication
import com.badlogic.gdx.backends.gwt.GwtApplicationConfiguration
import info.raa0121.exebattle.ExeBattle

class HtmlLauncher : GwtApplication() {

    override fun getConfig(): GwtApplicationConfiguration {
        return GwtApplicationConfiguration(480, 320)
    }

    override fun createApplicationListener(): ApplicationListener {
        return DuelSimulation()
    }
}